[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[lib]
name = "worker"
path = "src/lib.rs"

[dependencies]
serde = "1.0.195"
serde_json = "1.0.111"
image = "0.24.8"

# local dependencies
shared = { path = "../shared" }